### ISSUE TITLE
Issues using YesSql Stores

### ISSUE THREAD

**Issue by giannik** [elsa-workflows/elsa-orchard-core#2]
Using the Yes sql provider a number of errors appear when trying to create my first workflow
This is my startup config 
```
          services
                // Add services used for the workflows runtime.
                .AddElsa(elsa => elsa.AddYesSqlStores(config => config.UseSqlServer(Configuration.GetConnectionString("SqlServer"))))
       
               // .AddHttpActivities(options => options.Bind(Configuration.GetSection("Elsa:Http")))
                .AddEmailActivities(options => options.Bind(Configuration.GetSection("Elsa:Smtp")))
                .AddTimerActivities(options => options.Bind(Configuration.GetSection("Elsa:Timers")))

                // Add services used for the workflows dashboard.
                .AddElsaDashboard();

```

Firstly, when trying to publish my first workfloww from the dashboard I get an error : 
SqlException: Incorrect syntax near 'WorkflowDefinitionIndex'.

Secondly when trying to restart it crashes, because  it  calls  Elsa.Persistence.YesSql.StartupTasks.InitializeStoreTask.CreateTables() and tries to create the tables again.

**Comment by sfmskywalker** [comment]
> Firstly, when trying to publish my first workfloww from the dashboard I get an error : SqlException: Incorrect syntax near 'WorkflowDefinitionIndex'.

I'll create a separate issue for this - sounds like I need to update the YesSQL provider.

> Secondly when trying to restart it crashes, because it calls Elsa.Persistence.YesSql.StartupTasks.InitializeStoreTask.CreateTables() and tries to create the tables again.

That's odd. Although it's true that YesSQL will throw an exception, it should catch that error and ignore it. Is there code I can clone and look at?

**Comment by sfmskywalker** [comment]
Issue for the first issue: https://github.com/elsa-workflows/elsa-core/issues/119

**Comment by giannik** [comment]
The code I am using is the sample project for web host you have on github, just using yes sql stores. Here is the debug output from the console.


![image](https://user-images.githubusercontent.com/1516981/68074904-90abf680-fda9-11e9-953a-3cdd45b61494.png)

**Comment by sfmskywalker** [comment]
I found the issue and merge this PR as a fix: https://github.com/elsa-workflows/elsa-core/pull/121

**Comment by sfmskywalker** [comment]
Now that's fixed, I was thinking that we shouldn't have to provide the connection string ourselves: instead, the two stores (`YesSqlWorkflowDefinitionStore` and `YesSqlWorklowInstanceStore`) should simply receive the `ISession` service that is established by Orchard. 

I'll make a few small changes to make that work.

**Comment by giannik** [comment]
Yes, that would be perfect.
Maybe use the IDbConnectionAccessor  that is exposed by Orchard (https://orchardcore.readthedocs.io/en/dev/docs/reference/core/Data/).

**Comment by sfmskywalker** [comment]
The error should be fixed now.

Regarding `IDbConnectionAccessor`, it looks interesting. Feel free to use it from the Elsa Orchard Core project. But we can't use it from the `Elsa.Persistence.YesSql` package directly, because that should not have any dependencies on Orchard Core. What we can do however is have it support constructors that accept a `DbConnection` instance, which itself could be provided from `IDbConnectionAccessor`.
